//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DecisionArchitect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DecisionArchitect.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative for-relationships should not point to discarded decisions..
        /// </summary>
        internal static string AlternativeForNotPointTo {
            get {
                return ResourceManager.GetString("AlternativeForNotPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative for-relationships should only originate from tentative or discarded decisions..
        /// </summary>
        internal static string AlternativeForOnlyOriginateFrom {
            get {
                return ResourceManager.GetString("AlternativeForOnlyOriginateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caused by-relationships should not point to discarded decisions..
        /// </summary>
        internal static string CausedByNotPointTo {
            get {
                return ResourceManager.GetString("CausedByNotPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}
        ///[{1}].
        /// </summary>
        internal static string ChronologyDecisionName {
            get {
                return ResourceManager.GetString("ChronologyDecisionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you still want to create this relationship?.
        /// </summary>
        internal static string ConfirmCreateRelation {
            get {
                return ResourceManager.GetString("ConfirmCreateRelation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depends on-relationships should only point to tentative, decided, approved or challenged decisions..
        /// </summary>
        internal static string DependsOnOnlyPointTo {
            get {
                return ResourceManager.GetString("DependsOnOnlyPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is only a copy of the orginal decision. No modifications will be stored in this element. Do you want to open the original version of the decision instead?.
        /// </summary>
        internal static string DialogOpenLatestDecision {
            get {
                return ResourceManager.GetString("DialogOpenLatestDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open latest version of the decision.
        /// </summary>
        internal static string DialogOpenLatestDecisionTitle {
            get {
                return ResourceManager.GetString("DialogOpenLatestDecisionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please supply a name for the decision..
        /// </summary>
        internal static string ErrorNoNameForDecision {
            get {
                return ResourceManager.GetString("ErrorNoNameForDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a decicion view package..
        /// </summary>
        internal static string ErrorSelectDecisionViewPackage {
            get {
                return ResourceManager.GetString("ErrorSelectDecisionViewPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded by-relationships should not point to idea, tentative, discarded or rejected decisions..
        /// </summary>
        internal static string ExcludedByNotPointTo {
            get {
                return ResourceManager.GetString("ExcludedByNotPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded by-relationships should only originate from idea, tentative, discarded or rejected decisions..
        /// </summary>
        internal static string ExcludedOnlyOriginateFrom {
            get {
                return ResourceManager.GetString("ExcludedOnlyOriginateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure.
        /// </summary>
        internal static string ForcesViewConfigureButton {
            get {
                return ResourceManager.GetString("ForcesViewConfigureButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Decision named &quot;{0}&quot; already exists..
        /// </summary>
        internal static string ForcesViewDecisionExists {
            get {
                return ResourceManager.GetString("ForcesViewDecisionExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Force named &quot;{0}&quot; already exists with the Concern named &quot;{1}&quot;..
        /// </summary>
        internal static string ForcesViewForceExists {
            get {
                return ResourceManager.GetString("ForcesViewForceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force already exists.
        /// </summary>
        internal static string ForcesViewForceExistsWindowTitle {
            get {
                return ResourceManager.GetString("ForcesViewForceExistsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Decision Detail View.
        /// </summary>
        internal static string ForcesViewOpenDecisionInDetailView {
            get {
                return ResourceManager.GetString("ForcesViewOpenDecisionInDetailView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Decision in Diagram(s).
        /// </summary>
        internal static string ForcesViewOpenDecisionInDiagrams {
            get {
                return ResourceManager.GetString("ForcesViewOpenDecisionInDiagrams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Decisions.
        /// </summary>
        internal static string ForcesViewRemoveAllDecisions {
            get {
                return ResourceManager.GetString("ForcesViewRemoveAllDecisions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Forces.
        /// </summary>
        internal static string ForcesViewRemoveAllForces {
            get {
                return ResourceManager.GetString("ForcesViewRemoveAllForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Decision.
        /// </summary>
        internal static string ForcesViewRemoveDecision {
            get {
                return ResourceManager.GetString("ForcesViewRemoveDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Force.
        /// </summary>
        internal static string ForcesViewRemoveForce {
            get {
                return ResourceManager.GetString("ForcesViewRemoveForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&amp;Decision Architect.
        /// </summary>
        internal static string MenuAddIn {
            get {
                return ResourceManager.GetString("MenuAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manually.
        /// </summary>
        internal static string MenuBaselineManually {
            get {
                return ResourceManager.GetString("MenuBaselineManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On File Close.
        /// </summary>
        internal static string MenuBaselineOnClose {
            get {
                return ResourceManager.GetString("MenuBaselineOnClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Modification.
        /// </summary>
        internal static string MenuBaselineOnModify {
            get {
                return ResourceManager.GetString("MenuBaselineOnModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&amp;Baseline Options.
        /// </summary>
        internal static string MenuBaselineOptions {
            get {
                return ResourceManager.GetString("MenuBaselineOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Baseline.
        /// </summary>
        internal static string MenuCreateBaseline {
            get {
                return ResourceManager.GetString("MenuCreateBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Create Project Structure.
        /// </summary>
        internal static string MenuCreateProjectStructure {
            get {
                return ResourceManager.GetString("MenuCreateProjectStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&amp;Create Trace.
        /// </summary>
        internal static string MenuCreateTraces {
            get {
                return ResourceManager.GetString("MenuCreateTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&amp;Export.
        /// </summary>
        internal static string MenuExport {
            get {
                return ResourceManager.GetString("MenuExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Excel (Selected Forces view).
        /// </summary>
        internal static string MenuExportExcelForces {
            get {
                return ResourceManager.GetString("MenuExportExcelForces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Excel (All Forces views).
        /// </summary>
        internal static string MenuExportExcelForcesAll {
            get {
                return ResourceManager.GetString("MenuExportExcelForcesAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PowerPoint.
        /// </summary>
        internal static string MenuExportPowerPoint {
            get {
                return ResourceManager.GetString("MenuExportPowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate PowerPoint (Selected Decisions/Topics).
        /// </summary>
        internal static string MenuExportSelectedDecisionsPowerPoint {
            get {
                return ResourceManager.GetString("MenuExportSelectedDecisionsPowerPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Word  (Selected Decisions/Topics).
        /// </summary>
        internal static string MenuExportSelectedDecisionsWord {
            get {
                return ResourceManager.GetString("MenuExportSelectedDecisionsWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Word.
        /// </summary>
        internal static string MenuExportWord {
            get {
                return ResourceManager.GetString("MenuExportWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -&amp;Follow Trace(s).
        /// </summary>
        internal static string MenuFollowTraceDefault {
            get {
                return ResourceManager.GetString("MenuFollowTraceDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Traces defined.
        /// </summary>
        internal static string MenuFollowTraceNoTraces {
            get {
                return ResourceManager.GetString("MenuFollowTraceNoTraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Chronology View.
        /// </summary>
        internal static string MenuGenerateChronologicalVP {
            get {
                return ResourceManager.GetString("MenuGenerateChronologicalVP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing Element.
        /// </summary>
        internal static string MenuTraceToExistingElement {
            get {
                return ResourceManager.GetString("MenuTraceToExistingElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Decision.
        /// </summary>
        internal static string MenuTraceToNewDecision {
            get {
                return ResourceManager.GetString("MenuTraceToNewDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New Topic.
        /// </summary>
        internal static string MenuTraceToNewTopic {
            get {
                return ResourceManager.GetString("MenuTraceToNewTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision Architect.
        /// </summary>
        internal static string ModelValidationCategory {
            get {
                return ResourceManager.GetString("ModelValidationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1} {3} {2}).
        /// </summary>
        internal static string ModelValidationConnectorMessage {
            get {
                return ResourceManager.GetString("ModelValidationConnectorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (‹‹{1}›› {2}).
        /// </summary>
        internal static string ModelValidationElementMessage {
            get {
                return ResourceManager.GetString("ModelValidationElementMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Decision.
        /// </summary>
        internal static string NameSuggestionDecision {
            get {
                return ResourceManager.GetString("NameSuggestionDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Topic.
        /// </summary>
        internal static string NameSuggestionTopic {
            get {
                return ResourceManager.GetString("NameSuggestionTopic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every decision should have a unique name..
        /// </summary>
        internal static string NameUniqueness {
            get {
                return ResourceManager.GetString("NameUniqueness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A decision should not have a relation with itself..
        /// </summary>
        internal static string NoLoops {
            get {
                return ResourceManager.GetString("NoLoops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships should not originate from idea decisions..
        /// </summary>
        internal static string NotOriginateFromIdea {
            get {
                return ResourceManager.GetString("NotOriginateFromIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relationships should not point to idea decisions..
        /// </summary>
        internal static string NotPointToIdea {
            get {
                return ResourceManager.GetString("NotPointToIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces-relationships should only point to rejected decisions..
        /// </summary>
        internal static string ReplacesOnlyPointTo {
            get {
                return ResourceManager.GetString("ReplacesOnlyPointTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ‹‹{0}›› {1}: {2}.
        /// </summary>
        internal static string ReportingStakeholderInvolvmentLine {
            get {
                return ResourceManager.GetString("ReportingStakeholderInvolvmentLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} report successfully exported..
        /// </summary>
        internal static string ReportSuccessful {
            get {
                return ResourceManager.GetString("ReportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SaveDescription report as....
        /// </summary>
        internal static string SaveReportAs {
            get {
                return ResourceManager.GetString("SaveReportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces report was created successfully..
        /// </summary>
        internal static string SuccesfulForcesReportCreation {
            get {
                return ResourceManager.GetString("SuccesfulForcesReportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report was created successfully..
        /// </summary>
        internal static string SuccesfulReportCreation {
            get {
                return ResourceManager.GetString("SuccesfulReportCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string WarningCreateRelation {
            get {
                return ResourceManager.GetString("WarningCreateRelation", resourceCulture);
            }
        }
    }
}
